#!/bin/sh

option=$(printf "Power Off\nReboot" | rofi -dmenu -i -theme-str '@import "powermenu.rasi"')

case "$option" in
	"Power Off") poweroff ;;
	"Restart") reboot ;;
	# "Lock") swaylock ;;
	# "Lock") slock;;
	*) exit 1 ;;
esac
